In [1]:
import torch

c:\anaconda3\envs\std\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\anaconda3\envs\std\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
c:\anaconda3\envs\std\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
dtype = torch.float
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print('Using device:', device)

Using device: cuda:0


In [5]:
x = torch.tensor([[1], [2], [3], [4], [5]], dtype=dtype, device=device)
y = torch.tensor([[4], [8], [12], [16], [20]], dtype=dtype, device=device)

In [6]:
# 가중치를 저장하기 위해 무작위 값을 Tensor를 생성
# requires_grad = True로 설정하여 역전파 중에 이 Tensor들에 대한 변화도를
# 계산할 필요가 있음을 나타냄
w = torch.randn(1, 1, device=device, requires_grad=True, dtype=dtype)

# 랜던함게 설정된 w 값 학인
print(w)

tensor([[0.2575]], device='cuda:0', requires_grad=True)


In [7]:
learning_rate = 0.01

for t in range(15):
    y_pred = x.mm(w)

    # MSE loss
    loss = (y_pred - y).pow(2).sum()
    print(t, loss.item())

    # loss 에 대한 역전파 계산
    loss.backward()

    # 경사하강법(gradient descent)을 사용하여 가중치를 수동으로 갱신
    with torch.no_grad():
        w -= learning_rate * w.grad

        # 가중치 갱신 후에는 수동으로 변화도를 0으로 만듭니다.
        w.grad.zero_()

0 770.3624267578125
1 7.70364236831665
2 0.07703688740730286
3 0.0007704198942519724
4 7.705520147283096e-06
5 7.643939170520753e-08
6 8.003553375601768e-10
7 1.2050804798491299e-11
8 0.0
9 0.0
10 0.0
11 0.0
12 0.0
13 0.0
14 0.0


In [8]:
# W가 정확하게 학습이 되었는지 확인
test = torch.tensor([[6],[7],[8]], dtype=dtype, device=device)

y_pred = test.mm(w)

print(y_pred)

# W의 값을 재확인
print(w)

tensor([[24.],
        [28.],
        [32.]], device='cuda:0', grad_fn=<MmBackward0>)
tensor([[4.]], device='cuda:0', requires_grad=True)
