In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
z = np.array([3, 6, 9, 12, 15])

In [5]:
cov_mat = np.cov([x, y, z])
print(f'공분산 행렬 : \n{cov_mat}\n')

corr_mat = np.corrcoef([x, y, z])
print(f'상관 행렬 : \n{corr_mat}')

공분산 행렬 : 
[[ 2.5  5.   7.5]
 [ 5.  10.  15. ]
 [ 7.5 15.  22.5]]

상관 행렬 : 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# 다중공선성 판단
threshold = 0.7

print('다중 공선성 판단 : ')
for i in range(corr_mat.shape[0]):  # 세로 방향 순회
    for j in range(i + 1, corr_mat.shape[1]):  # 가로 방향 순회
        # i번째 행을 순회할 때 i번째 열 이전의 모든 값은 대각선 왼쪽에 해당하는 값이므로
        # i번째 열 이후 값들을 순회하도록 범위를 제한
        if abs(corr_mat[i, j])> threshold:
            print(f'변수 {i + 1}과 변수 {j + 1} 사이에 다중 공선성 존재')

다중 공선성 판단 : 
변수 1과 변수 2 사이에 다중 공선성 존재
변수 1과 변수 3 사이에 다중 공선성 존재
변수 2과 변수 3 사이에 다중 공선성 존재
