In [31]:
import numpy as np
import seaborn as sns
import pandas as pd
# problem 1 
# input : 배열을 직접 입력하지 말고, numpy의 함수를 써서 아래와 같이 생성 (a,b 모두)

# a = array([[0, 1, 2, 3, 4],
#       [5, 6, 7, 8, 9]])
a = np.arange(10).reshape(2,5)
# b = array([[1, 1, 1, 1, 1],
#       [1, 1, 1, 1, 1]])
b = np.ones((2,5))
# output : 
# array([[0, 1, 2, 3, 4],
#       [5, 6, 7, 8, 9],
#       [1, 1, 1, 1, 1],
#       [1, 1, 1, 1, 1]])
np.vstack((a,b))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
# problem 2 
# input : 
a_2d = np.array([[4,4,4],[5,5,5],[6,6,6]])
b_1d = np.array([1,2,3])

# output :
# array([[3, 3, 3],
#       [3, 3, 3],
#       [3, 3, 3]])
b = b_1d.reshape(3,-1)
c = a_2d - b
c

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])