In [1]:
import numpy as np
import timeit

In [2]:
b = range(1000000)

%timeit [i+1 for i in b]

457 ms ± 87.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
a = np.arange(1000000)

%timeit a+1

4.47 ms ± 808 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [51]:

start_time = timeit.default_timer()

# code you want to evaluate
size = 10000
arr = np.arange(size**2).reshape(size,size)
arr[np.where(arr>10**5)] = 0

elapsed = timeit.default_timer() - start_time


In [52]:
print(elapsed)
print(arr)

2.5278602969997337
[[    0     1     2 ...  9997  9998  9999]
 [10000 10001 10002 ... 19997 19998 19999]
 [20000 20001 20002 ... 29997 29998 29999]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]


In [53]:

start_time = timeit.default_timer()

size = 10000
arr = np.arange(size**2).reshape(size,size)
arr[arr>10**5] = 0

elapsed = timeit.default_timer() - start_time


In [54]:
print(elapsed)
print(arr)

0.6449301640000158
[[    0     1     2 ...  9997  9998  9999]
 [10000 10001 10002 ... 19997 19998 19999]
 [20000 20001 20002 ... 29997 29998 29999]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]


In [55]:

start_time = timeit.default_timer()
size = 10000
arr = np.arange(size**2).reshape(size,size)
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if(arr[i,j] > 10**5):
            arr[i,j] = 0

elapsed = timeit.default_timer() - start_time

In [56]:
print(elapsed)
print(arr)

69.28496348999988
[[    0     1     2 ...  9997  9998  9999]
 [10000 10001 10002 ... 19997 19998 19999]
 [20000 20001 20002 ... 29997 29998 29999]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
