In [22]:
import numpy as np
def main():
    print("1차원 array")
    array = np.arange(10)
    print(array)
    # Q1. array의 자료형을 출력해보세요.
    print(type(array))
    # Q2. array의 차원을 출력해보세요.
    print(array.ndim)
    # Q3. array의 모양을 출력해보세요.
    print(array.shape)
    # Q4. array의 크기를 출력해보세요.
    print(array.size)
    # Q5. array의 dtype(data type)을 출력해보세요.
    print(array.dtype)
    # Q6. array의 5번째 요소를 출력해보세요.
    print(array[4])
    # Q7. array의 4번째 요소부터 5번째 요소까지 출력해보세요.
    print(array[3:6])
if __name__ == "__main__":
    main()

1차원 array
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
int32
4
[3 4 5]


In [21]:
def main():
    array = np.array([1,2,3,4,5])
    array2 = np.array([5,4,3,2,1])
    print(array)
    # Q1. array에 5를 더한 값을 출력해보세요.
    print(array + 5)
    # Q2. array에 5를 뺀 값을 출력해보세요.
    print(array - 5)
    # Q3. array에 5를 곱한 값을 출력해보세요.
    print(array * 5)
    # Q4. array를 5로 나눈 값을 출력해보세요.
    print(array / 5)
    # Q5. array에 array2를 더한 값을 출력해보세요.    
    print("배열끼리의 덧셈 : ", array + array2)
    
    # Q6. array에 array2를 뺀 값을 출력해보세요.
    print("배열끼리의 뺄셈 : ", array - array2)
    
if __name__ == "__main__":
    main()

[1 2 3 4 5]
[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
배열끼리의 덧셈 :  [6 6 6 6 6]
배열끼리의 뺄셈 :  [-4 -2  0  2  4]
